### ISSUE TITLE
Provide a command for only avy-zapping with a prefix

### ISSUE THREAD

**Issue by Wilfred** [cute-jumper/avy-zap#3]
I've just upgraded, and 7225e2a70bdd65cea5ed9476a12a16b209bbdcb6 caught me by surprise. I see you've added a note in the readme (thanks :) ) but this is a breaking change and stops avy-zap being a drop-in replacement for ace-jump-zap.

For my usage, zapping up to the first instance of a character is the most common case, so I prefer that being the default. What was the motivation for swapping the behaviour? Would you be open to adding an option that restores the previous behaviour?

**Comment by cute-jumper** [comment]
Sorry for the surprise! I found myself using avy version more often, and since `avy-zap` is the package name, the default behavior being the avy version seems more consistent to me. But no problem, we should provide an option for people who want the old behaviors. See https://github.com/cute-jumper/avy-zap/commit/ee3a2ad9911384e21537bc641a2f794dd192bbe8. You can now set `avy-zap-dwim-prefer-avy` to nil to restore the old behaviors.

**Comment by Wilfred** [comment]
Perfect, thank you very much :)
